### PR TITLE
[overview:arch] Add additional diagram focusing on protocols

### PR DESCRIPTION
**Pull request by lucendio**
(fill in your PR description)

## Checklist:

Please tick the following before making your PR:

* [X] I ran `make` on this branch to build the docs and there are **no WARNINGs**.
* [X] After running `make`, I looked at the output by opening build/html/index.html in a browser and I'm satisfied with the rendering.

### CODE REVIEW

**Comment by lucendio** [comment]
@jschaul in case some source for this diagram is lying around somewhere (e.g. drawio), would you mind adding it to this PR?

**Comment by jschaul** [comment]
See https://github.com/zinfra/backend-wiki/tree/master/diagrams/architecture - sources are next to the PNGs.

Note that the protocol inside kubernetes depends on the networking plugin chosen, and may therefore be encrypted. I think @flokli suggested to use something new that does transport encryption between pods so then the diagram can be adjusted.

**Comment by lucendio** [comment]
> See https://github.com/zinfra/backend-wiki/tree/master/diagrams/architecture - sources are next to the PNGs.

Ahh, I'm sorry. I was expecting it to be in the wiki repo. Would you be okay with me moving the source to this repo here and link to it on our wiki page?

**Comment by jschaul** [comment]
> > See https://github.com/zinfra/backend-wiki/tree/master/diagrams/architecture - sources are next to the PNGs.
> 
> Ahh, I'm sorry. I was expecting it to be in the wiki repo. Would you be okay with me moving the source to this repo here and link to it on our wiki page?

Please do.

**Pull request merged**
