### PR TITLE
Edits

### PR DESCRIPTION
**Pull request by fisx**

### CODE REVIEW

**Comment by fisx** [comment]
@arianvp since I'm being rude to the text you wrote (I think), do you want to take a quick look?

**Comment by arianvp** [comment]
Thanks! Looks good!

**Comment by arianvp** [comment]
@fisx I just noticed you sneaked in a symlink `src -> source`. Was that on purpose?

**Comment by fisx** [comment]
> @fisx I just noticed you sneaked in a symlink `src -> source`. Was that on purpose?

yes.  :)

Was that a bad idea?  I always stumble over the unusual name when I need to navigate there, but if we don't want it under git control I can of course keep the link in my local working copy without committing it.

**Comment by arianvp** [comment]
I would also approve a PR  renaming `source` to `src`     I think that's less confusing than having two entries.

**Comment by jschaul** [comment]
Moved files from `source` to `src` for ergonomic purposes, directly on master: https://github.com/wireapp/wire-docs/commit/70f3e98a19c225e864d86dd9ca65da4aef291eec. Please rebase your PRs if needed.

**Pull request merged**
