### PR TITLE
manual backoffice procedure

### PR DESCRIPTION
**Pull request by jschaul**
manual backoffice procedure (if backoffice is not available)

## Checklist:

* [x] I ran `make` on this branch to build the docs and there are **no WARNINGs**.
* [x] After running `make`, I looked at the output by opening build/html/index.html in a browser and I'm satisfied with the rendering.

### CODE REVIEW

**Comment by julialongtin** [comment]
/mnt/src/how-to/api-client-perspective/index.rst: WARNING: document isn't included in any toctree

I got a warning when running make against this branch.

**Comment by jschaul** [comment]
> /mnt/src/how-to/api-client-perspective/index.rst: WARNING: document isn't included in any toctree
> 
> I got a warning when running make against this branch.

Yes, correct. This PR doesn't introduce any new warnings, however. The warning stems from https://github.com/wireapp/wire-docs/pull/17 which introduced a page without an index page for it. I plan to write an index page for that (and maybe port another page) at some point. This is unrelated to the current PR, though.

**Comment by julialongtin** [comment]
This looks good to me, but the name of this is a bit unclear, compared to the names of all of the other things on the howto index page.

**Comment by jschaul** [comment]
> This looks good to me, but the name of this is a bit unclear, compared to the names of all of the other things on the howto index page.

Any ideas for a better naming of the header?

**Comment by julialongtin** [comment]
I'd switch this to either "manually searching for users" or "investigative tasks". it is likely we will have more than just cassandra documents on this page, eventually.

**Pull request merged**
